### ISSUE TITLE
On Tablet mode, once checked out how do you get back to store? No top menu

### ISSUE THREAD

**Issue by mivajenn** [mivaecommerce/readytheme-ironwool#14]
is that normal?

![screen shot 2016-09-21 at 10 32 12 am 2](https://cloud.githubusercontent.com/assets/11448089/18721766/c9e440e0-7fe6-11e6-8978-d796f67f4175.png)

**Comment by influxweb** [comment]
Clicking the logo will do it. That should be the same functionality as in Suivant.

**Comment by mivajenn** [comment]
Ok this doesn't work on the server site, but it does on my 96 site. thanks.
