### ISSUE TITLE
On optional subscription, no term is required

### ISSUE THREAD

**Issue by mivajenn** [mivaecommerce/readytheme-ironwool#15]
When you add subscription as an option, and they click on subscription instead of one time purchase, it does not require you to choose a term.
![screen shot 2016-09-21 at 10 32 12 am 2](https://cloud.githubusercontent.com/assets/11448089/18722464/bdf480da-7fe9-11e6-88ab-972bb6dc2158.png)

**Comment by influxweb** [comment]
That is the accepted functionality as referenced here: mivaecommerce/readytheme-storyteller#26
