### ISSUE TITLE
Split payment issue with Iron and Wool ReadyTheme

### ISSUE THREAD

**Issue by mivajenn** [mivaecommerce/readytheme-ironwool#2]
I have simple validation installed along with check payment. When I have given myself credit, and try to check out applying only some of that credit, I cannot check any of my credit cards. It won't let me select both a credit card and select apply my credit. 

If I select a credit card and then apply credit, it takes me to the next screen where I can apply partial payment, when I go to the next screen, it now only gives me the box for check number - no ability to pay remaining balance by credit card. Please see attached images.

![screen shot 2015-04-17 at 4 48 16 pm](https://cloud.githubusercontent.com/assets/11448089/7212832/7a69b9c4-e522-11e4-8465-e3af7cf93126.png)

![screen shot 2015-04-17 at 4 48 24 pm](https://cloud.githubusercontent.com/assets/11448089/7212833/7f15233c-e522-11e4-8cef-b3acc990baa9.png)

![screen shot 2015-04-17 at 4 48 32 pm](https://cloud.githubusercontent.com/assets/11448089/7212834/828be640-e522-11e4-9ddb-ccccf2d57c8d.png)

**Comment by influxweb** [comment]
@mivajenn - Can you verify that you have both of the payment methods items assigned to the OPAY page?

**Comment by influxweb** [comment]
Okay, looks like this will need some cleaning up. In the mean time, you can correct the issue by making the following changes to the OPAY Details:

At line 132, replace:
```<mvt:assign name="g.totalPayment" value="'hide'" />```
With:
```<mvt:assign name="g.totalPayment" value="'display: none;'" />```

At line 134, replace:
```<div id="payment-additional" class="&mvt:global:totalPayment;">```
With:
```<div id="payment-additional" style="&mvt:global:totalPayment;">```

**Comment by mivajenn** [comment]
what does this mean?

On Aug 24, 2015, at 11:08 AM, Matt Zimmermann <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #2<https://github.com/mivaecommerce/readytheme-ironwool/issues/2>.

—
Reply to this email directly or view it on GitHub<https://github.com/mivaecommerce/readytheme-ironwool/issues/2#event-390862803>.


Jenn Randolph

Graphic Designer / Miva, Inc.
www.miva.com<http://www.miva.com/>

Twitter<http://www.twitter.com/mivamerchant> | Facebook<http://www.facebook.com/mivamerchant> | Instagram<http://www.instagram.com/mivamerchant> | Vimeo<http://www.vimeo.com/mivamerchant> | Blog<http://www.mivamerchant.com/blog>

[http://www.mivamerchant.com/images/new-images/miva-email-sig.gif]<http://www.miva.com/>

**Comment by influxweb** [comment]
The issue has been resolved and closed. Since you were the one who submitted it, you received a notification of the change.
