### ISSUE TITLE
credit card icons missing

### ISSUE THREAD

**Issue by mivajenn** [mivaecommerce/readytheme-ironwool#9]
![screen shot 2016-09-21 at 9 49 20 am 2](https://cloud.githubusercontent.com/assets/11448089/18720546/1f5be696-7fe1-11e6-967e-3717c261c047.png)

I loaded this in my 96test store and I didn't see the same problem. So maybe it's just our server issue?
![screen shot 2016-09-21 at 9 52 24 am 2](https://cloud.githubusercontent.com/assets/11448089/18720557/2d8fa716-7fe1-11e6-8235-65b0cecc96a7.png)

**Comment by bheyde** [comment]
We just don't have JBC or Diners Club icons included in the themes. I'll remove those options from the demo store and that should solve this.
